# Generated by Django 4.0.5 on 2022-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(default='media/images/default.jpeg', upload_to='images/'),
        ),
    ]
